-- ============================================================
-- Component: Authentication & User Management
-- File: 01_auth_and_users.sql
-- Description: Core users table supporting 4 primary roles:
--              'admin', 'student', 'club_adviser', 'ssc'
-- ============================================================

CREATE TABLE IF NOT EXISTS `users` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(60) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `first_name` VARCHAR(100) NOT NULL,
  `last_name` VARCHAR(100) NOT NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  `role` ENUM('admin', 'student', 'club_adviser', 'ssc') NOT NULL DEFAULT 'student',
  `profile_pic` VARCHAR(255) DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_users_username` (`username`),
  UNIQUE KEY `uq_users_email` (`email`),
  KEY `idx_users_role` (`role`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Official Initial Seed Accounts (from SYSTEM_ACCOUNTS.md)
INSERT INTO `users` (`id`, `username`, `email`, `first_name`, `last_name`, `password_hash`, `role`) VALUES
(1, 'bsit.student', 'brianjoshua@student.bcp.edu.ph', 'Juan', 'Santos', '$2y$10$hOurKEX9y7pG8Kc8UQgBnugBGPJGqda3QdCJkWiNMGGM.vOjjoTSe', 'student'),
(2, 'bshm.student', 'bshm@student.bcp.edu.ph', 'Maria', 'Cruz', '$2y$10$hOurKEX9y7pG8Kc8UQgBnugBGPJGqda3QdCJkWiNMGGM.vOjjoTSe', 'student'),
(3, 'bsais.student', 'bsais@student.bcp.edu.ph', 'Jose', 'Reyes', '$2y$10$hOurKEX9y7pG8Kc8UQgBnugBGPJGqda3QdCJkWiNMGGM.vOjjoTSe', 'student'),
(4, 'bstm.student', 'bstm@student.bcp.edu.ph', 'Ana', 'Dela Cruz', '$2y$10$hOurKEX9y7pG8Kc8UQgBnugBGPJGqda3QdCJkWiNMGGM.vOjjoTSe', 'student'),
(5, 'bsoa.student', 'bsoa@student.bcp.edu.ph', 'Carlos', 'Garcia', '$2y$10$hOurKEX9y7pG8Kc8UQgBnugBGPJGqda3QdCJkWiNMGGM.vOjjoTSe', 'student'),
(6, 'bse.student', 'bse@student.bcp.edu.ph', 'Liza', 'Ramos', '$2y$10$hOurKEX9y7pG8Kc8UQgBnugBGPJGqda3QdCJkWiNMGGM.vOjjoTSe', 'student'),
(7, 'bsba.student', 'bsba@student.bcp.edu.ph', 'Ramon', 'Villanueva', '$2y$10$hOurKEX9y7pG8Kc8UQgBnugBGPJGqda3QdCJkWiNMGGM.vOjjoTSe', 'student'),
(8, 'bsis.student', 'bsis@student.bcp.edu.ph', 'Patricia', 'Aquino', '$2y$10$hOurKEX9y7pG8Kc8UQgBnugBGPJGqda3QdCJkWiNMGGM.vOjjoTSe', 'student'),
(9, 'bscpe.student', 'bscpe@student.bcp.edu.ph', 'Mark', 'Bautista', '$2y$10$hOurKEX9y7pG8Kc8UQgBnugBGPJGqda3QdCJkWiNMGGM.vOjjoTSe', 'student'),
(10, 'bspsych.student', 'bspsych@student.bcp.edu.ph', 'Jenny', 'Navarro', '$2y$10$hOurKEX9y7pG8Kc8UQgBnugBGPJGqda3QdCJkWiNMGGM.vOjjoTSe', 'student'),
(11, 'bscrim.student', 'bscrim@student.bcp.edu.ph', 'Rico', 'Fernandez', '$2y$10$hOurKEX9y7pG8Kc8UQgBnugBGPJGqda3QdCJkWiNMGGM.vOjjoTSe', 'student'),
(12, 'bspe.student', 'bspe@student.bcp.edu.ph', 'Sheila', 'Santos', '$2y$10$hOurKEX9y7pG8Kc8UQgBnugBGPJGqda3QdCJkWiNMGGM.vOjjoTSe', 'student'),
(13, 'tle.student', 'tle@student.bcp.edu.ph', 'Angelo', 'Torres', '$2y$10$hOurKEX9y7pG8Kc8UQgBnugBGPJGqda3QdCJkWiNMGGM.vOjjoTSe', 'student'),
(14, 'bseled.student', 'bseled@student.bcp.edu.ph', 'Claire', 'Mendoza', '$2y$10$hOurKEX9y7pG8Kc8UQgBnugBGPJGqda3QdCJkWiNMGGM.vOjjoTSe', 'student'),
(15, 'bsseed.student', 'bsseed@student.bcp.edu.ph', 'Danilo', 'Pascual', '$2y$10$hOurKEX9y7pG8Kc8UQgBnugBGPJGqda3QdCJkWiNMGGM.vOjjoTSe', 'student'),
(16, 'bslis.student', 'bslis@student.bcp.edu.ph', 'Rowena', 'Espinosa', '$2y$10$hOurKEX9y7pG8Kc8UQgBnugBGPJGqda3QdCJkWiNMGGM.vOjjoTSe', 'student'),
(17, 'cssec.adviser', 'cssec@adviser.bcp.edu.ph', 'Alex', 'Reyes', '$2y$10$oyeEZ5UhDsC3TIM8NoF0eeovu8cU0q4bpCHtRNCTE/NUo1czdBdxq', 'club_adviser'),
(18, 'acads.adviser', 'acads@adviser.bcp.edu.ph', 'Mark', 'Velo', '$2y$10$oyeEZ5UhDsC3TIM8NoF0eeovu8cU0q4bpCHtRNCTE/NUo1czdBdxq', 'club_adviser'),
(19, 'aces.adviser', 'aces@adviser.bcp.edu.ph', 'Elena', 'Ramos', '$2y$10$oyeEZ5UhDsC3TIM8NoF0eeovu8cU0q4bpCHtRNCTE/NUo1czdBdxq', 'club_adviser'),
(20, 'aiss.adviser', 'aiss@adviser.bcp.edu.ph', 'Clara', 'Tan', '$2y$10$oyeEZ5UhDsC3TIM8NoF0eeovu8cU0q4bpCHtRNCTE/NUo1czdBdxq', 'club_adviser'),
(21, 'bliss.adviser', 'bliss@adviser.bcp.edu.ph', 'Robert', 'Cruz', '$2y$10$oyeEZ5UhDsC3TIM8NoF0eeovu8cU0q4bpCHtRNCTE/NUo1czdBdxq', 'club_adviser'),
(22, 'brave.adviser', 'brave@adviser.bcp.edu.ph', 'Diana', 'Gomez', '$2y$10$oyeEZ5UhDsC3TIM8NoF0eeovu8cU0q4bpCHtRNCTE/NUo1czdBdxq', 'club_adviser'),
(23, 'cjsu.adviser', 'cjsu@adviser.bcp.edu.ph', 'Jose', 'Mercado', '$2y$10$oyeEZ5UhDsC3TIM8NoF0eeovu8cU0q4bpCHtRNCTE/NUo1czdBdxq', 'club_adviser'),
(24, 'eyo.adviser', 'eyo@adviser.bcp.edu.ph', 'Lisa', 'Santos', '$2y$10$oyeEZ5UhDsC3TIM8NoF0eeovu8cU0q4bpCHtRNCTE/NUo1czdBdxq', 'club_adviser'),
(25, 'galaw.adviser', 'galaw@adviser.bcp.edu.ph', 'Manuel', 'Cruz', '$2y$10$oyeEZ5UhDsC3TIM8NoF0eeovu8cU0q4bpCHtRNCTE/NUo1czdBdxq', 'club_adviser'),
(26, 'gems.adviser', 'gems@adviser.bcp.edu.ph', 'Anna', 'Reyes', '$2y$10$oyeEZ5UhDsC3TIM8NoF0eeovu8cU0q4bpCHtRNCTE/NUo1czdBdxq', 'club_adviser'),
(27, 'gold.adviser', 'gold@adviser.bcp.edu.ph', 'Karen', 'Lim', '$2y$10$oyeEZ5UhDsC3TIM8NoF0eeovu8cU0q4bpCHtRNCTE/NUo1czdBdxq', 'club_adviser'),
(28, 'jfinex.adviser', 'jfinex@adviser.bcp.edu.ph', 'Manuel', 'Cruz', '$2y$10$oyeEZ5UhDsC3TIM8NoF0eeovu8cU0q4bpCHtRNCTE/NUo1czdBdxq', 'club_adviser'),
(29, 'hrs.adviser', 'hrs@adviser.bcp.edu.ph', 'Alex', 'Reyes', '$2y$10$oyeEZ5UhDsC3TIM8NoF0eeovu8cU0q4bpCHtRNCTE/NUo1czdBdxq', 'club_adviser'),
(30, 'jma.adviser', 'jma@adviser.bcp.edu.ph', 'Sarah', 'Mercado', '$2y$10$oyeEZ5UhDsC3TIM8NoF0eeovu8cU0q4bpCHtRNCTE/NUo1czdBdxq', 'club_adviser'),
(31, 'lakas.adviser', 'lakas@adviser.bcp.edu.ph', 'Clara', 'Tan', '$2y$10$oyeEZ5UhDsC3TIM8NoF0eeovu8cU0q4bpCHtRNCTE/NUo1czdBdxq', 'club_adviser'),
(32, 'lapis.adviser', 'lapis@adviser.bcp.edu.ph', 'Diana', 'Gomez', '$2y$10$oyeEZ5UhDsC3TIM8NoF0eeovu8cU0q4bpCHtRNCTE/NUo1czdBdxq', 'club_adviser'),
(33, 'libro.adviser', 'libro@adviser.bcp.edu.ph', 'Robert', 'Cruz', '$2y$10$oyeEZ5UhDsC3TIM8NoF0eeovu8cU0q4bpCHtRNCTE/NUo1czdBdxq', 'club_adviser'),
(34, 'omega.adviser', 'omega@adviser.bcp.edu.ph', 'Jose', 'Mercado', '$2y$10$oyeEZ5UhDsC3TIM8NoF0eeovu8cU0q4bpCHtRNCTE/NUo1czdBdxq', 'club_adviser'),
(35, 'psychsoc.adviser', 'psychsoc@adviser.bcp.edu.ph', 'Lisa', 'Santos', '$2y$10$oyeEZ5UhDsC3TIM8NoF0eeovu8cU0q4bpCHtRNCTE/NUo1czdBdxq', 'club_adviser'),
(36, 'rsd.adviser', 'rsd@adviser.bcp.edu.ph', 'Anna', 'Reyes', '$2y$10$oyeEZ5UhDsC3TIM8NoF0eeovu8cU0q4bpCHtRNCTE/NUo1czdBdxq', 'club_adviser'),
(37, 'sigma.adviser', 'sigma@adviser.bcp.edu.ph', 'Karen', 'Lim', '$2y$10$oyeEZ5UhDsC3TIM8NoF0eeovu8cU0q4bpCHtRNCTE/NUo1czdBdxq', 'club_adviser'),
(38, 'techs.adviser', 'techs@adviser.bcp.edu.ph', 'Alex', 'Reyes', '$2y$10$oyeEZ5UhDsC3TIM8NoF0eeovu8cU0q4bpCHtRNCTE/NUo1czdBdxq', 'club_adviser'),
(39, 'tts.adviser', 'tts@adviser.bcp.edu.ph', 'Sarah', 'Mercado', '$2y$10$oyeEZ5UhDsC3TIM8NoF0eeovu8cU0q4bpCHtRNCTE/NUo1czdBdxq', 'club_adviser'),
(40, 'wika.adviser', 'wika@adviser.bcp.edu.ph', 'Clara', 'Tan', '$2y$10$oyeEZ5UhDsC3TIM8NoF0eeovu8cU0q4bpCHtRNCTE/NUo1czdBdxq', 'club_adviser'),
(41, 'acac.adviser', 'acac@adviser.bcp.edu.ph', 'Sarah', 'Mercado', '$2y$10$oyeEZ5UhDsC3TIM8NoF0eeovu8cU0q4bpCHtRNCTE/NUo1czdBdxq', 'club_adviser'),
(42, 'cesc.adviser', 'cesc@adviser.bcp.edu.ph', 'Mark', 'Velo', '$2y$10$oyeEZ5UhDsC3TIM8NoF0eeovu8cU0q4bpCHtRNCTE/NUo1czdBdxq', 'club_adviser'),
(43, 'ebcpct.adviser', 'ebcpct@adviser.bcp.edu.ph', 'Mark', 'Velo', '$2y$10$oyeEZ5UhDsC3TIM8NoF0eeovu8cU0q4bpCHtRNCTE/NUo1czdBdxq', 'club_adviser'),
(44, 'rcyc.adviser', 'rcyc@adviser.bcp.edu.ph', 'Elena', 'Cruz', '$2y$10$oyeEZ5UhDsC3TIM8NoF0eeovu8cU0q4bpCHtRNCTE/NUo1czdBdxq', 'club_adviser'),
(45, 'smc.adviser', 'smc@adviser.bcp.edu.ph', 'Mark', 'Velo', '$2y$10$oyeEZ5UhDsC3TIM8NoF0eeovu8cU0q4bpCHtRNCTE/NUo1czdBdxq', 'club_adviser'),
(46, 'allstar.adviser', 'allstar@adviser.bcp.edu.ph', 'Sarah', 'Mercado', '$2y$10$oyeEZ5UhDsC3TIM8NoF0eeovu8cU0q4bpCHtRNCTE/NUo1czdBdxq', 'club_adviser'),
(47, 'bforce.adviser', 'bforce@adviser.bcp.edu.ph', 'Sarah', 'Mercado', '$2y$10$oyeEZ5UhDsC3TIM8NoF0eeovu8cU0q4bpCHtRNCTE/NUo1czdBdxq', 'club_adviser'),
(48, 'creative.adviser', 'creative@adviser.bcp.edu.ph', 'Sarah', 'Mercado', '$2y$10$oyeEZ5UhDsC3TIM8NoF0eeovu8cU0q4bpCHtRNCTE/NUo1czdBdxq', 'club_adviser'),
(49, 'cdc.adviser', 'cdc@adviser.bcp.edu.ph', 'Sarah', 'Mercado', '$2y$10$oyeEZ5UhDsC3TIM8NoF0eeovu8cU0q4bpCHtRNCTE/NUo1czdBdxq', 'club_adviser'),
(50, 'dlc.adviser', 'dlc@adviser.bcp.edu.ph', 'Sarah', 'Mercado', '$2y$10$oyeEZ5UhDsC3TIM8NoF0eeovu8cU0q4bpCHtRNCTE/NUo1czdBdxq', 'club_adviser'),
(51, 'ikatlong.adviser', 'ikatlong@adviser.bcp.edu.ph', 'Sarah', 'Mercado', '$2y$10$oyeEZ5UhDsC3TIM8NoF0eeovu8cU0q4bpCHtRNCTE/NUo1czdBdxq', 'club_adviser'),
(52, 'image.adviser', 'image@adviser.bcp.edu.ph', 'Sarah', 'Mercado', '$2y$10$oyeEZ5UhDsC3TIM8NoF0eeovu8cU0q4bpCHtRNCTE/NUo1czdBdxq', 'club_adviser'),
(53, 'sikat.adviser', 'sikat@adviser.bcp.edu.ph', 'Sarah', 'Mercado', '$2y$10$oyeEZ5UhDsC3TIM8NoF0eeovu8cU0q4bpCHtRNCTE/NUo1czdBdxq', 'club_adviser'),
(54, 'uv.adviser', 'uv@adviser.bcp.edu.ph', 'Sarah', 'Mercado', '$2y$10$oyeEZ5UhDsC3TIM8NoF0eeovu8cU0q4bpCHtRNCTE/NUo1czdBdxq', 'club_adviser'),
(55, 'peer.adviser', 'peer@adviser.bcp.edu.ph', 'Elena', 'Cruz', '$2y$10$oyeEZ5UhDsC3TIM8NoF0eeovu8cU0q4bpCHtRNCTE/NUo1czdBdxq', 'club_adviser'),
(56, 'newslink.adviser', 'newslink@adviser.bcp.edu.ph', 'Elena', 'Cruz', '$2y$10$oyeEZ5UhDsC3TIM8NoF0eeovu8cU0q4bpCHtRNCTE/NUo1czdBdxq', 'club_adviser'),
(57, 'gadcg.adviser', 'gadcg@adviser.bcp.edu.ph', 'Elena', 'Cruz', '$2y$10$j7Rk01Bv3gzqpnF6fBxSQOfX8.3RJuwU85MADI6YvO4AEytawnSz2', 'club_adviser'),
(58, 'ssc.officer', 'ssc@bcp.edu.ph', 'SSC', 'Officer', '$2y$10$IglOXnR9y1VmIwFNgiKNROrb4LlUsTexydSjISeGKHx1Fp.nJC/hq', 'ssc'),
(59, 'scc.admin', 'admin@bcp.edu.ph', 'System', 'Admin', '$2y$10$v5YfjzzK2ZuRD88Sp9.Xp.I/vAFHzXIIR4WPZ2bU5HWchSYY2vCT6', 'admin')
ON DUPLICATE KEY UPDATE `first_name`=VALUES(`first_name`), `last_name`=VALUES(`last_name`), `password_hash`=VALUES(`password_hash`), `role`=VALUES(`role`);
